8-4/Fernando/Web_App/Controllers/Bitacora/BitacoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_App.Controllers.Bitacora
{
    public class BitacoraController : Controller
    {
        // GET: Bitacora
        public ActionResult vBitacora()
        {
            return View();
        }
    }
}

8-4/Fernando/Web_App/Controllers/RolController/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_App.Controllers
{
    public class RolController : Controller
    {
        public ActionResult vRol()
        {
            return View();
        }
    }
}

8-4/Fernando/Web_App/Controllers/TipoTrabajoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_App.Controllers
{
    public class TipoTrabajoController : Controller
    {
        public ActionResult vTipoTrabajo()
        {
            return View();
        }
    }
}

8-4/Fernando/Web_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MASTER</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/Content/compiled-4.14.1.min.css">
    <!-- MDBootstrap Datatables  -->
    <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="~/Content/style.css">


    <!-- jQuery -->
    <script type="text/javascript" src="~/Scripts/jquery.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    @*<script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://z9t4u9f6.stackpathcdn.com/wp-content/themes/mdbootstrap4/js/bundles/4.14.1/compiled.0.min.js?ver=4.14.1"></script>
        <script src="https://brandflow.net/static/general/bf-core.min.js?ts=1584823562877"></script>
        <script src="https://z9t4u9f6.stackpathcdn.com/wp-content/plugins/woocommerce-multilingual/res/js/front-scripts.min.js?ver=4.7.9"></script>*@
    <script type="text/javascript" src="~/Scripts/compiled.min.js"></script>
    <script src="~/Scripts/Services/SelectAjax/selectComponent.js"></script>
    <!-- Control Actions Script -->
    <script src="~/Scripts/Views/ControlActions.js"></script>
    <!-- Data Tables Script-->
    <script src="~/Scripts/addons/datatables.min.js"></script>
    <!-- FontAwesome Script-->
    <script src="https://kit.fontawesome.com/a993a78eb6.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/Services/Helper/Prototypes.js"></script>
</head>
<body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark primary-color py-3">

        <a class="navbar-brand" href="#">
            <img src="https://mdbootstrap.com/img/logo/mdb-transparent.png" height="30" alt="mdb logo">
        </a>

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">Bejuco</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">
                        Inicio
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Empresas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Trabajos</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Un lindo dropdown</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons">

                <li class="nav-item">

                </li>

                <li class="nav-item avatar dropdown">
                    <a class="nav-link p-0 dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Juana de Arco
                        <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-5.jpg" class="rounded-circle z-depth-0 pl-1"
                             alt="avatar image" height="35">
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-default"
                         aria-labelledby="navbarDropdownMenuLink-333">
                        <a class="dropdown-item" href="#">Perfil</a>
                        <a class="dropdown-item" href="#">Cerrar sesión</a>

                    </div>

                </li>
            </ul>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <div class="alert alert-danger alert-dismissable" style="display: none;" id="alert_container">
        <button type="button" class="close" onclick="$('.alert').hide()">×</button>
        <span id="alert_message"></span>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>



</body>
</html>

8-4/Fernando/Web_App/Views/Shared/_LayoutAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MASTER</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/Content/compiled-4.14.1.min.css">
    <!-- MDBootstrap Datatables  -->
    <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="~/Content/style.css">


    <!-- jQuery -->
    <script type="text/javascript" src="~/Scripts/jquery.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/Scripts/compiled.min.js"></script>
    <script src="~/Scripts/Services/SelectAjax/selectComponent.js"></script>
    <!-- Control Actions Script -->
    <script src="~/Scripts/Views/ControlActions.js"></script>
    <!-- Data Tables Script-->
    <script src="~/Scripts/addons/datatables.min.js"></script>
    <!-- FontAwesome Script-->
    <script src="https://kit.fontawesome.com/a993a78eb6.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/Services/Helper/Prototypes.js"></script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar elegant-color">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand brand-font" href="#">
                <strong>MASTER</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--Left-->
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Inicio
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("vBitacora", "Bitacora")">Bitácora</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Estadísticas</a>
                    </li>
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Sistema</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("vEspecialidades", "Especialidades")">Especialidades</a>
                            <a class="dropdown-item" href="@Url.Action("vTipoTrabajo", "TipoTrabajo")">Tipos de Trabajo</a>
                            <a class="dropdown-item" href="@Url.Action("vRol", "Rol")">Roles</a>
                            <a class="dropdown-item" href="@Url.Action("vTerminosServicio", "TerminosServicio")">Términos de Servicio</a>
                            <a class="dropdown-item" href="#">Membresías</a>
                            <a class="dropdown-item" href="#">Solicitudes de Trabajo</a>
                        </div>
                    </li>

                </ul>
                <!--Right-->
                <ul class="navbar-nav ml-auto nav-flex-icons">

                    <li class="nav-item avatar dropdown">
                        <a class="nav-link p-0 dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Juana de Arco
                            <i class="fas fa-user"></i>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right dropdown-dark"
                             aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="@Url.Action("vConfiguracion", "Configuracion")">Configuraciones</a>
                            <a class="dropdown-item" href="#">Cerrar sesión</a>

                        </div>

                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

    <div class="alert alert-danger alert-dismissable" style="display: none;" id="alert_container">
        <button type="button" class="close" onclick="$('.alert').hide()">×</button>
        <span id="alert_message"></span>
    </div>

    <div class="container body-content pt-xl-5">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>



</body>
</html>

8-4/Fernando/Web_App/Views/Shared/_LayoutProveedorFisico.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MASTER</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/Content/compiled-4.14.1.min.css">
    <!-- MDBootstrap Datatables  -->
    <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="~/Content/style.css">


    <!-- jQuery -->
    <script type="text/javascript" src="~/Scripts/jquery.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/Scripts/compiled.min.js"></script>
    <script src="~/Scripts/Services/SelectAjax/selectComponent.js"></script>
    <!-- Control Actions Script -->
    <script src="~/Scripts/Views/ControlActions.js"></script>
    <!-- Data Tables Script-->
    <script src="~/Scripts/addons/datatables.min.js"></script>
    <!-- FontAwesome Script-->
    <script src="https://kit.fontawesome.com/a993a78eb6.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/Services/Helper/Prototypes.js"></script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar elegant-color">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand brand-font" href="#">
                <strong>MASTER</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--Left-->
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Inicio
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Trabajos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Trabajadores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Estadísticas</a>
                    </li>

                </ul>
                <!--Right-->
                <ul class="navbar-nav ml-auto nav-flex-icons">

                    <li class="nav-item avatar dropdown">
                        <a class="nav-link p-0 dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Juana de Arco
                            <i class="fas fa-user"></i>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right dropdown-dark"
                             aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="@Url.Action("vConfiguracion", "Configuracion")">Configuraciones</a>
                            <a class="dropdown-item" href="#">Cerrar sesión</a>

                        </div>

                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

    

    <div class="container body-content pt-xl-5">

        <div class="alert alert-danger alert-dismissable mt-3" style="display: none;" id="alert_container">
            <button type="button" class="close" onclick="$('.alert').hide()">×</button>
            <span id="alert_message"></span>
        </div>

        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>



</body>
</html>

8-4/Fernando/Web_App/Views/Shared/_LayoutProveedorJuridico.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MASTER</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/Content/compiled-4.14.1.min.css">
    <!-- MDBootstrap Datatables  -->
    <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="~/Content/style.css">


    <!-- jQuery -->
    <script type="text/javascript" src="~/Scripts/jquery.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/Scripts/compiled.min.js"></script>
    <script src="~/Scripts/Services/SelectAjax/selectComponent.js"></script>
    <!-- Control Actions Script -->
    <script src="~/Scripts/Views/ControlActions.js"></script>
    <!-- Data Tables Script-->
    <script src="~/Scripts/addons/datatables.min.js"></script>
    <!-- FontAwesome Script-->
    <script src="https://kit.fontawesome.com/a993a78eb6.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/Services/Helper/Prototypes.js"></script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar elegant-color">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand brand-font" href="#">
                <strong>MASTER</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--Left-->
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Inicio
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Trabajos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Estadísticas</a>
                    </li>

                </ul>
                <!--Right-->
                <ul class="navbar-nav ml-auto nav-flex-icons">

                    <li class="nav-item avatar dropdown">
                        <a class="nav-link p-0 dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Juana de Arco
                            <i class="fas fa-user"></i>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right dropdown-dark"
                             aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="@Url.Action("vConfiguracion", "Configuracion")">Configuraciones</a>
                            <a class="dropdown-item" href="#">Cerrar sesión</a>

                        </div>

                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

    <div class="alert alert-danger alert-dismissable" style="display: none;" id="alert_container">
        <button type="button" class="close" onclick="$('.alert').hide()">×</button>
        <span id="alert_message"></span>
    </div>

    <div class="container body-content pt-xl-5">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>



</body>
</html>