8-4/Fernando/Web_App/Controllers/Configuracion/ConfiguracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_App.Controllers.Configuracion
{
    public class ConfiguracionController : Controller
    {
        // GET: Configuracion
        public ActionResult vConfiguracion()
        {
            return View();
        }
    }
}

8-4/Fernando/Web_App/Controllers/Documento/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_App.Controllers.Documento
{
    public class DocumentoController : Controller
    {
        // GET: Documento
        public ActionResult vDocumentoFisico()
        {
            return View("vDocumento", "_LayoutProveedorFisico");
        }

        public ActionResult vDocumentoJuridico()
        {
            return View("vDocumento", "_LayoutProveedorJuridico");
        }
    }
}

8-4/Fernando/Web_App/Views/Configuracion/vConfiguracion.cshtml
@using Web_App.AppCode.Helper.Language;
@{
    Layout = "~/Views/Shared/_LayoutProveedorJuridico.cshtml";
}

<!--- Welcome Section -->
<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12 pt-4">
            <h1 class="brand-font pt-4">Configuraciones</h1>
        </div>

        <hr>

        <div class="col-12 pb-3">
            <p class="lead">Administre sus preferencias a la hora de utilizar la plataforma</p>
        </div>
    </div>
</div>

<div class="jumbotron mt-4">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h2 class="display-4">Licencias</h2>
                <p class="lead">Adquiera o renueve su licencia MASTER para seguir construyendo su camino en nuestra plataforma</p>
            </div>

            <div class="col-3">
                <a class="btn btn-primary btn-lg mt-5" href="@Url.Action("vMembresiaFisico", "Membresia")" role="button">Ir ahora</a>
            </div>
        </div>
    </div>
</div>

<div class="jumbotron mt-4">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h2 class="display-4">Documentos</h2>
                <p class="lead">Agregue los documentos legales de su empresa. Estos serán utilizados para trámites legales o procesos de legitimización en la plataforma.</p>
            </div>

            <div class="col-3">
                <a class="btn btn-primary btn-lg mt-5" href="@Url.Action("vDocumentoFisico", "Documento")" role="button">Ir ahora</a>
            </div>
        </div>
    </div>
</div>

<div class="jumbotron mt-4">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h2 class="display-4">Moneda</h2>
                <p class="lead">Configure la moneda en que visualiza sus transacciones y recibe sus ganancias</p>
            </div>

            <div class="col-3">
                <a class="btn btn-primary btn-lg mt-5" href="#" role="button">Ir ahora</a>
            </div>
        </div>
    </div>
</div>